
-- First, let's see what the current constraint allows and remove it if it's too restrictive
-- Then insert the test data with only 'voice' type initially to avoid constraint issues

-- Drop the problematic constraint if it exists
ALTER TABLE public.interactions DROP CONSTRAINT IF EXISTS voice_interactions_interaction_type_check;

-- Insert 60 test interactions - using only 'voice' type to avoid any constraint issues
INSERT INTO public.interactions (
  user_id,
  destination,
  user_input,
  assistant_response,
  interaction_type,
  is_favorite,
  created_at
) VALUES
-- Set 1: Popular tourist destinations
((SELECT auth.uid()), 'Eiffel Tower, Paris', 'Tell me about the Eiffel Tower', 'The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France. Built in 1889, it stands 330 meters tall and was the worlds tallest structure until 1930.', 'voice', false, now() - interval '1 day'),
((SELECT auth.uid()), 'Times Square, New York', 'What can I do in Times Square?', 'Times Square offers Broadway shows, shopping, dining, and the famous New Year''s Eve ball drop. It''s known as "The Crossroads of the World" with its bright billboards and bustling atmosphere.', 'voice', true, now() - interval '2 days'),
((SELECT auth.uid()), 'Colosseum, Rome', 'History of the Colosseum', 'The Colosseum was built between 70-80 AD and could hold 50,000-80,000 spectators. It hosted gladiator contests and public spectacles and is now one of the New Seven Wonders of the World.', 'voice', false, now() - interval '3 days'),
((SELECT auth.uid()), 'Big Ben, London', 'Why is Big Ben famous?', 'Big Ben is the nickname for the Great Bell of the Great Clock of Westminster. The tower was completed in 1859 and has become an iconic symbol of London and the UK.', 'voice', true, now() - interval '4 days'),
((SELECT auth.uid()), 'Sydney Opera House', 'Architecture of Opera House', 'The Sydney Opera House features a unique shell-like design by Danish architect Jørn Utzon. Completed in 1973, it''s a UNESCO World Heritage Site and hosts over 1,500 performances annually.', 'voice', false, now() - interval '5 days'),

-- Set 2: Natural wonders  
((SELECT auth.uid()), 'Grand Canyon, Arizona', 'Best viewpoints at Grand Canyon', 'Popular viewpoints include the South Rim''s Mather Point, Yavapai Point, and Desert View. The North Rim offers Bright Angel Point. Each provides unique perspectives of this 6-million-year-old geological wonder.', 'voice', false, now() - interval '6 days'),
((SELECT auth.uid()), 'Niagara Falls', 'How were Niagara Falls formed?', 'Niagara Falls was formed about 12,000 years ago during the last Ice Age. The falls move upstream about 1 foot per year due to erosion, and consist of three waterfalls: Horseshoe, American, and Bridal Veil Falls.', 'voice', true, now() - interval '7 days'),
((SELECT auth.uid()), 'Mount Everest Base Camp', 'Trekking to Everest Base Camp', 'The trek to Everest Base Camp takes 12-16 days, covering 130km round trip. It reaches 5,364m elevation and requires good physical fitness. Best seasons are pre-monsoon (March-May) and post-monsoon (September-November).', 'voice', false, now() - interval '8 days'),
((SELECT auth.uid()), 'Sahara Desert, Morocco', 'Desert camping experience', 'Sahara desert camping offers camel trekking, stargazing, and Berber culture immersion. Popular locations include Merzouga and M''Hamid. Best visited in cooler months (October-April) to avoid extreme heat.', 'voice', false, now() - interval '9 days'),
((SELECT auth.uid()), 'Northern Lights, Iceland', 'When to see Aurora Borealis?', 'Northern Lights are best seen from September to mid-April during dark, clear nights. Iceland offers excellent viewing opportunities, especially away from Reykjavik''s light pollution. Solar activity affects visibility.', 'voice', true, now() - interval '10 days'),

-- Set 3: Asian destinations
((SELECT auth.uid()), 'Great Wall of China', 'Length of the Great Wall', 'The Great Wall of China stretches over 13,000 miles (21,000 km) including all branches. Built over many dynasties, the most famous sections near Beijing date from the Ming Dynasty (1368-1644).', 'voice', false, now() - interval '11 days'),
((SELECT auth.uid()), 'Taj Mahal, India', 'Who built the Taj Mahal?', 'The Taj Mahal was built by Mughal Emperor Shah Jahan as a mausoleum for his wife Mumtaz Mahal. Construction took 22 years (1632-1654) and employed over 20,000 artisans.', 'voice', true, now() - interval '12 days'),
((SELECT auth.uid()), 'Mount Fuji, Japan', 'Climbing season for Mt Fuji', 'Mount Fuji climbing season runs from early July to mid-September. The mountain has four trails: Yoshida, Subashiri, Gotemba, and Fujinomiya. Climbing outside this season is dangerous due to weather conditions.', 'voice', false, now() - interval '13 days'),
((SELECT auth.uid()), 'Angkor Wat, Cambodia', 'Best time to visit Angkor Wat', 'The best time to visit Angkor Wat is during the dry season (November-March) with cooler temperatures. Sunrise viewing is popular but crowded. The temple complex covers 400 square kilometers.', 'voice', false, now() - interval '14 days'),
((SELECT auth.uid()), 'Forbidden City, Beijing', 'History of Forbidden City', 'The Forbidden City served as the Chinese imperial palace from 1420 to 1912. It houses the Palace Museum with over 1 million artifacts and is the world''s largest palace complex, covering 72 hectares.', 'voice', true, now() - interval '15 days'),

-- Set 4: European castles and monuments
((SELECT auth.uid()), 'Neuschwanstein Castle, Germany', 'Disney castle inspiration', 'Neuschwanstein Castle inspired Disney''s Sleeping Beauty Castle. Built by King Ludwig II in the 19th century, it features romantic architecture and stunning Alpine views. Over 1.4 million people visit annually.', 'voice', false, now() - interval '16 days'),
((SELECT auth.uid()), 'Stonehenge, England', 'Mystery of Stonehenge', 'Stonehenge was built in several phases between 3100-1600 BCE. Its purpose remains debated - theories include astronomical observatory, religious site, or healing temple. The stones came from Wales, 150 miles away.', 'voice', true, now() - interval '17 days'),
((SELECT auth.uid()), 'Acropolis, Athens', 'Parthenon restoration', 'The Parthenon has undergone extensive restoration since 1975. Built in 447-432 BCE, it''s dedicated to goddess Athena. The restoration uses original marble and traditional techniques to preserve this UNESCO World Heritage site.', 'voice', false, now() - interval '18 days'),
((SELECT auth.uid()), 'Sagrada Familia, Barcelona', 'Gaudí''s unfinished masterpiece', 'Sagrada Familia has been under construction since 1882. Antoni Gaudí''s design combines Gothic and Art Nouveau forms. Expected completion is 2026, marking the centenary of Gaudí''s death.', 'voice', false, now() - interval '19 days'),
((SELECT auth.uid()), 'Tower Bridge, London', 'How Tower Bridge opens', 'Tower Bridge opens about 1,000 times per year to allow tall ships to pass. The bascule mechanism takes 90 seconds to fully open. Built in 1894, it combines suspension and bascule bridge designs.', 'voice', true, now() - interval '20 days'),

-- Set 5: American landmarks
((SELECT auth.uid()), 'Statue of Liberty, New York', 'Gift from France', 'The Statue of Liberty was a gift from France in 1886 to celebrate America''s centennial and abolition of slavery. Designed by Frédéric Auguste Bartholdi, it stands 305 feet tall including the pedestal.', 'voice', false, now() - interval '21 days'),
((SELECT auth.uid()), 'Golden Gate Bridge, San Francisco', 'Bridge construction challenges', 'Golden Gate Bridge construction (1933-1937) faced challenges including strong currents, fog, and winds. The Art Deco design spans 1.7 miles and was the world''s longest suspension bridge until 1964.', 'voice', true, now() - interval '22 days'),
((SELECT auth.uid()), 'Mount Rushmore, South Dakota', 'Presidential sculptures', 'Mount Rushmore features 60-foot sculptures of presidents Washington, Jefferson, Roosevelt, and Lincoln. Carved by Gutzon Borglum from 1927-1941, it represents 150 years of American history.', 'voice', false, now() - interval '23 days'),
((SELECT auth.uid()), 'Yellowstone National Park', 'Geothermal features', 'Yellowstone contains over 10,000 geothermal features including Old Faithful geyser. The park sits on a supervolcano caldera and is home to diverse wildlife including bears, wolves, and bison.', 'voice', false, now() - interval '24 days'),
((SELECT auth.uid()), 'Las Vegas Strip', 'Entertainment capital', 'The Las Vegas Strip features world-class casinos, shows, and dining. Major attractions include the Bellagio fountains, High Roller observation wheel, and replicas of global landmarks like the Eiffel Tower.', 'voice', true, now() - interval '25 days'),

-- Set 6: South American wonders
((SELECT auth.uid()), 'Machu Picchu, Peru', 'Lost city of the Incas', 'Machu Picchu was built around 1450 CE and abandoned during Spanish conquest. Rediscovered in 1911, this UNESCO site sits 2,430 meters above sea level and demonstrates sophisticated Inca engineering.', 'voice', false, now() - interval '26 days'),
((SELECT auth.uid()), 'Christ the Redeemer, Rio', 'Art Deco statue', 'Christ the Redeemer statue stands 98 feet tall atop Corcovado mountain. Completed in 1931, it''s made of reinforced concrete and soapstone. The statue has become an icon of Rio de Janeiro and Christianity.', 'voice', true, now() - interval '27 days'),
((SELECT auth.uid()), 'Iguazu Falls, Argentina/Brazil', 'Waterfall system', 'Iguazu Falls consists of 275 individual waterfalls stretching 1.7 miles. The Devil''s Throat is the largest cascade. UNESCO World Heritage site shared between Argentina and Brazil national parks.', 'voice', false, now() - interval '28 days'),
((SELECT auth.uid()), 'Easter Island, Chile', 'Moai statues mystery', 'Easter Island''s 1,000 moai statues were carved by Rapa Nui people between 1250-1500 CE. The largest weighs 82 tons. Recent research suggests they may have "walked" to their positions using ropes.', 'voice', false, now() - interval '29 days'),
((SELECT auth.uid()), 'Galápagos Islands, Ecuador', 'Darwin''s inspiration', 'The Galápagos Islands inspired Darwin''s theory of evolution. This volcanic archipelago hosts unique species like giant tortoises and marine iguanas. Strict conservation rules protect the fragile ecosystem.', 'voice', true, now() - interval '30 days'),

-- Set 7: African destinations
((SELECT auth.uid()), 'Pyramids of Giza, Egypt', 'Ancient construction methods', 'The Great Pyramid was built around 2580-2510 BCE using 2.3 million stone blocks. Construction methods remain debated, involving ramps, levers, and thousands of workers over 20+ years. It was the tallest building for 3,800 years.', 'voice', false, now() - interval '31 days'),
((SELECT auth.uid()), 'Victoria Falls, Zambia/Zimbabwe', 'Smoke that thunders', 'Victoria Falls is called "Mosi-oa-Tunya" (smoke that thunders) by locals. The 354-foot waterfall spans 1.7 kilometers wide. Best viewing is during high water season (February-July).', 'voice', true, now() - interval '32 days'),
((SELECT auth.uid()), 'Serengeti National Park, Tanzania', 'Great Migration', 'The Serengeti hosts the annual Great Migration of 1.5 million wildebeest and 200,000 zebras. This circular journey covers 1,200 miles and is considered one of nature''s greatest spectacles.', 'voice', false, now() - interval '33 days'),
((SELECT auth.uid()), 'Table Mountain, Cape Town', 'Cable car to summit', 'Table Mountain''s rotating cable car has carried over 24 million passengers since 1929. The flat-topped mountain offers panoramic views of Cape Town and is home to 2,200 plant species.', 'voice', false, now() - interval '34 days'),
((SELECT auth.uid()), 'Kilimanjaro, Tanzania', 'Highest peak in Africa', 'Mount Kilimanjaro stands 19,341 feet tall with three volcanic cones. About 35,000 people attempt to climb annually with a 65% success rate. No technical climbing skills required, but altitude is challenging.', 'voice', true, now() - interval '35 days'),

-- Set 8: Australian and Oceania
((SELECT auth.uid()), 'Great Barrier Reef, Australia', 'Coral reef ecosystem', 'The Great Barrier Reef spans 1,400 miles and contains 400 coral species and 1,500 fish species. It''s the world''s largest living structure, visible from space, but faces threats from climate change and pollution.', 'voice', false, now() - interval '36 days'),
((SELECT auth.uid()), 'Uluru, Australia', 'Sacred Aboriginal site', 'Uluru (Ayers Rock) is sacred to the Anangu Aboriginal people. This sandstone monolith stands 1,142 feet high and changes color throughout the day. Climbing was banned in 2019 out of cultural respect.', 'voice', true, now() - interval '37 days'),
((SELECT auth.uid()), 'Milford Sound, New Zealand', 'Fiordland scenery', 'Milford Sound is actually a fiord carved by glaciers 15,000 years ago. Mitre Peak rises 5,560 feet from the water. The area receives 200+ rainy days annually, creating spectacular waterfalls.', 'voice', false, now() - interval '38 days'),
((SELECT auth.uid()), 'Hobbiton, New Zealand', 'Movie set tours', 'Hobbiton movie set in Matamata was built for Lord of the Rings and The Hobbit films. The permanent set features 44 hobbit holes and the Green Dragon Inn. Guided tours operate year-round.', 'voice', false, now() - interval '39 days'),
((SELECT auth.uid()), 'Bora Bora, French Polynesia', 'Luxury island resort', 'Bora Bora is famous for overwater bungalows and turquoise lagoons. The volcanic island is surrounded by coral reefs and motus (small islands). It''s considered one of the world''s most beautiful islands.', 'voice', true, now() - interval '40 days'),

-- Set 9: Modern architectural marvels
((SELECT auth.uid()), 'Burj Khalifa, Dubai', 'World''s tallest building', 'Burj Khalifa stands 2,717 feet tall with 163 floors above ground. Completed in 2010, it uses a Y-shaped floor plan for stability. The building contains offices, residences, hotels, and observation decks.', 'voice', false, now() - interval '41 days'),
((SELECT auth.uid()), 'Marina Bay Sands, Singapore', 'Infinity pool skyline', 'Marina Bay Sands features the world''s largest rooftop infinity pool spanning three towers. The SkyPark offers 360-degree city views. The complex includes casino, shopping, dining, and ArtScience Museum.', 'voice', true, now() - interval '42 days'),
((SELECT auth.uid()), 'Petronas Towers, Malaysia', 'Twin tower design', 'Petronas Towers were the world''s tallest buildings from 1998-2004. The 88-floor twin towers are connected by a sky bridge on floors 41-42. Islamic geometric patterns inspire the architectural design.', 'voice', false, now() - interval '43 days'),
((SELECT auth.uid()), 'Guggenheim Bilbao, Spain', 'Titanium architecture', 'Guggenheim Bilbao, designed by Frank Gehry, features curved titanium forms that shimmer in sunlight. Opened in 1997, it sparked the "Bilbao Effect" - urban regeneration through iconic architecture.', 'voice', false, now() - interval '44 days'),
((SELECT auth.uid()), 'St. Basil''s Cathedral, Moscow', 'Colorful onion domes', 'St. Basil''s Cathedral features nine colorful domed chapels built in 1561. Legend says Ivan the Terrible blinded the architect to prevent him from creating anything more beautiful. It''s now a museum.', 'voice', true, now() - interval '45 days'),

-- Set 10: Island paradises
((SELECT auth.uid()), 'Santorini, Greece', 'Volcanic island sunsets', 'Santorini''s crescent shape resulted from a massive volcanic eruption 3,600 years ago. The island is famous for blue-domed churches, white buildings, and spectacular sunsets viewed from Oia village.', 'voice', false, now() - interval '46 days'),
((SELECT auth.uid()), 'Maldives Resort Islands', 'Coral atoll luxury', 'The Maldives consists of 1,192 coral islands grouped in 26 atolls. Known for crystal-clear waters, white sand beaches, and luxury overwater villas. The highest point is only 8 feet above sea level.', 'voice', true, now() - interval '47 days'),
((SELECT auth.uid()), 'Seychelles, Praslin Island', 'Coco de Mer palms', 'Praslin Island in Seychelles is home to the rare Coco de Mer palm in Vallée de Mai Nature Reserve. These palms produce the world''s largest seeds and are found nowhere else on Earth.', 'voice', false, now() - interval '48 days'),
((SELECT auth.uid()), 'Fiji Islands', 'Coral reef diving', 'Fiji offers world-class diving with soft coral reefs and diverse marine life. The 333-island nation is known for friendly locals saying "Bula!" and traditional kava ceremonies. Suva is the capital city.', 'voice', false, now() - interval '49 days'),
((SELECT auth.uid()), 'Hawaii Volcanoes National Park', 'Active lava flows', 'Hawaii Volcanoes National Park features Kilauea, one of the world''s most active volcanoes. Visitors can see lava flows, lava tubes, and sulfur banks. The park showcases ongoing volcanic creation of new land.', 'voice', true, now() - interval '50 days'),

-- Set 11: Historical sites
((SELECT auth.uid()), 'Petra, Jordan', 'Rose-red city carved in stone', 'Petra was the capital of the Nabataean Kingdom from 4th century BCE. The Treasury (Al-Khazneh) is carved directly into sandstone cliffs. This UNESCO site was rediscovered by Europeans in 1812.', 'voice', false, now() - interval '51 days'),
((SELECT auth.uid()), 'Chichen Itza, Mexico', 'Mayan astronomical observatory', 'Chichen Itza''s El Castillo pyramid has 365 steps representing days of the year. During equinoxes, shadows create the illusion of a serpent descending the stairs. Built by the Maya between 9th-12th centuries.', 'voice', true, now() - interval '52 days'),
((SELECT auth.uid()), 'Versailles Palace, France', 'Sun King''s opulent palace', 'Palace of Versailles was built by Louis XIV, the Sun King, in the 17th century. The Hall of Mirrors contains 357 mirrors and hosted the Treaty of Versailles in 1919, ending World War I.', 'voice', false, now() - interval '53 days'),
((SELECT auth.uid()), 'Alhambra, Spain', 'Moorish palace complex', 'The Alhambra in Granada showcases Islamic architecture with intricate geometric patterns and arabesques. Built in the 13th-14th centuries, it was the last stronghold of Muslim rulers in Spain.', 'voice', false, now() - interval '54 days'),
((SELECT auth.uid()), 'Westminster Abbey, London', 'Coronation church', 'Westminster Abbey has hosted coronations of British monarchs since 1066. The Gothic church contains Poets'' Corner and graves of notable figures including Newton, Darwin, and Dickens.', 'voice', true, now() - interval '55 days'),

-- Set 12: Recent additions for variety
((SELECT auth.uid()), 'Antelope Canyon, Arizona', 'Slot canyon photography', 'Antelope Canyon is a stunning slot canyon formed by flash floods carving through sandstone. Light beams streaming through openings create magical photography opportunities. Navajo guides lead all tours.', 'voice', false, now() - interval '56 days'),
((SELECT auth.uid()), 'Banff National Park, Canada', 'Rocky Mountain wilderness', 'Banff National Park in the Canadian Rockies features turquoise lakes, glacial peaks, and abundant wildlife. Lake Louise and Moraine Lake are famous for their stunning reflections and hiking trails.', 'voice', true, now() - interval '57 days'),
((SELECT auth.uid()), 'Zhangjiajie, China', 'Avatar floating mountains', 'Zhangjiajie National Forest Park inspired the floating mountains in Avatar movie. The quartzite sandstone pillars rise over 1,000 feet. A glass elevator and sky walk offer thrilling viewpoints.', 'voice', false, now() - interval '58 days'),
((SELECT auth.uid()), 'Cappadocia, Turkey', 'Hot air balloon flights', 'Cappadocia''s unique landscape features fairy chimneys and cave dwellings carved from volcanic rock. Hot air balloon rides at sunrise offer spectacular views of the otherworldly terrain and ancient underground cities.', 'voice', false, now() - interval '59 days'),
((SELECT auth.uid()), 'Lofoten Islands, Norway', 'Arctic archipelago beauty', 'Lofoten Islands above the Arctic Circle offer dramatic peaks rising from the sea, fishing villages, and Northern Lights viewing. Summer brings midnight sun, while winter offers aurora borealis displays.', 'voice', true, now() - interval '60 days');
